# Generated by Django 2.2.6 on 2019-10-12 11:40

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32, verbose_name='Виробник')),
                ('slug', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марка',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32, verbose_name='Категорія')),
                ('slug', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='TestVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Назва автомобіля')),
                ('image', models.ImageField(upload_to='test_img/', verbose_name='Зображення')),
                ('price_usd', models.CharField(max_length=32, verbose_name='Ціна в у.о.')),
                ('price_uah', models.CharField(max_length=32, verbose_name='Ціна в грн.')),
                ('mileage', models.CharField(max_length=32, verbose_name='Пробіг')),
                ('city', models.CharField(max_length=32, verbose_name='Місто')),
                ('fuel', models.IntegerField(choices=[(1, 'Дизель'), (2, 'Бензин'), (3, 'Газ/Бензин'), (4, 'Електро'), (5, 'Гібрид')], verbose_name='Тип пального')),
                ('gearbox', models.IntegerField(choices=[(1, 'Ручна'), (2, 'Автоматична')], verbose_name='Тип КПП')),
                ('numberplate', models.CharField(max_length=8, verbose_name='Номери')),
            ],
            options={
                'verbose_name': 'Тестова штучка',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('brand', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категорія'), chained_model_field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категорія'), on_delete=django.db.models.deletion.CASCADE, to='main.Brand')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Моделі',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категорія'),
        ),
    ]
