# Generated by Django 2.2.6 on 2019-10-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='avatar',
        ),
    ]
